//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public System.Guid Id { get; set; }
        public System.Guid TeamId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Goals { get; set; }
        public int YellowCards { get; set; }
        public int RedCards { get; set; }
        public Nullable<int> GamesPlayed { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
